export const teamList = [
  {
    name: 'Sebastian Parafjańczuk',
    role: 'Team Lead',
    github: 'https://github.com/SebastianPrf',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U053K53S8LE-gcf609fafe9c-512',
  },
  {
    name: 'Sylwia Bruszewska',
    role: 'Scrum Master',
    github: 'https://github.com/sylwiabruszewska',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U052Z2QKD3J-ee70167b0f18-512',
  },
  {
    name: 'Anna Dudys',
    role: 'Developer',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U0522L64AAJ-e15902d98f8f-512',
  },
  {
    name: 'Darek Ścierański',
    role: 'Developer',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U052JGW3P6F-496a76da18e8-512',
  },
  {
    name: 'Joanna Mikusinska-Nowak',
    role: 'Developer',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U053BBUJMK2-46c7aaf9f1ee-512',
  },
  {
    name: 'Karol Trombala',
    role: 'Developer',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U057L4PMTK7-bd1057584168-512',
  },
  {
    name: 'Łukasz Wiśniewski',
    role: 'Developer',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U052K6SM6TF-fbcec6a9b9db-512',
  },
  {
    name: 'Mikołaj Marcinkowski',
    role: 'Developer',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U051NEGMF0V-gc7c1aaa80c6-512',
  },
  {
    name: 'Monika Cichmon',
    role: 'Developer',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U052N9CJJ7K-g01ac3dbd874-512',
  },
  {
    name: 'Rafał Pelc',
    role: 'Developer',
    github: 'hhttps://github.com/RafalPelc',
    linkedin: 'https://www.linkedin.com/',
    photo: 'https://ca.slack-edge.com/T04V0BAHQP6-U0529K9NTD5-ga8eda55e7b2-512',
  },
];
